import { Accessibility, ChartPie, Download, MapPin, Users, UsersRound } from 'lucide-react'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { Button, PageHeader } from '../components/UI'
import { useApp } from '../context/AppContext'
import { formatNumber } from '../lib/utils'

export default function Beneficiaries() {
  const { data, language, t } = useApp()
  const totals = data.beneficiaries.reduce((acc, item) => ({ households: acc.households + item.households, men: acc.men + item.men, women: acc.women + item.women, boys: acc.boys + item.boys, girls: acc.girls + item.girls, pwd: acc.pwd + item.peopleWithDisabilities }), { households: 0, men: 0, women: 0, boys: 0, girls: 0, pwd: 0 })
  const people = totals.men + totals.women + totals.boys + totals.girls
  const gender = [{ name: language === 'ar' ? 'ذكور' : 'Male', value: totals.men + totals.boys, color: '#0f766e' }, { name: language === 'ar' ? 'إناث' : 'Female', value: totals.women + totals.girls, color: '#f59e0b' }]
  return <>
    <PageHeader eyebrow={language === 'ar' ? 'المساءلة والوصول' : 'Accountability & reach'} title={t('beneficiaries')} description={language === 'ar' ? 'تابع الوصول والتوزيع الديموغرافي دون عرض بيانات شخصية حساسة.' : 'Monitor reach and demographics without exposing sensitive personal data.'} actions={<Button variant="secondary" icon={<Download size={17}/>}>{t('export')}</Button>} />
    <section className="stats-grid beneficiary-stats"><article className="stat-card"><div className="stat-card__icon stat-card__icon--teal"><UsersRound/></div><div><span>{language === 'ar' ? 'الأفراد المسجلون' : 'People registered'}</span><strong>{formatNumber(people, language)}</strong><small>{data.beneficiaries.length} {language === 'ar' ? 'مجموعات بيانات' : 'data groups'}</small></div></article><article className="stat-card"><div className="stat-card__icon stat-card__icon--blue"><Users/></div><div><span>{language === 'ar' ? 'الأسر' : 'Households'}</span><strong>{formatNumber(totals.households, language)}</strong><small>{language === 'ar' ? 'متوسط 4 أفراد' : '4 people average'}</small></div></article><article className="stat-card"><div className="stat-card__icon stat-card__icon--amber"><Accessibility/></div><div><span>{language === 'ar' ? 'ذوو الإعاقة' : 'People with disabilities'}</span><strong>{formatNumber(totals.pwd, language)}</strong><small>{Math.round(totals.pwd / people * 100)}% {language === 'ar' ? 'من الإجمالي' : 'of total'}</small></div></article></section>
    <section className="dashboard-grid beneficiaries-grid"><article className="card"><header className="card__header"><div><h2>{language === 'ar' ? 'التوزيع حسب الجنس والعمر' : 'Gender and age distribution'}</h2><p>{language === 'ar' ? 'بيانات مجمعة لجميع المشروعات' : 'Aggregated across all projects'}</p></div><ChartPie size={20}/></header><div className="gender-chart"><ResponsiveContainer width="45%" height={240}><PieChart><Pie data={gender} dataKey="value" innerRadius={60} outerRadius={88} paddingAngle={4} stroke="none">{gender.map(item => <Cell key={item.name} fill={item.color}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="demographic-list"><div><span><i style={{background:'#0f766e'}}/>{language === 'ar' ? 'الرجال' : 'Men'}</span><strong>{formatNumber(totals.men, language)}</strong></div><div><span><i style={{background:'#14b8a6'}}/>{language === 'ar' ? 'الأولاد' : 'Boys'}</span><strong>{formatNumber(totals.boys, language)}</strong></div><div><span><i style={{background:'#f59e0b'}}/>{language === 'ar' ? 'النساء' : 'Women'}</span><strong>{formatNumber(totals.women, language)}</strong></div><div><span><i style={{background:'#fbbf24'}}/>{language === 'ar' ? 'البنات' : 'Girls'}</span><strong>{formatNumber(totals.girls, language)}</strong></div></div></div></article><article className="card"><header className="card__header"><div><h2>{language === 'ar' ? 'الوصول حسب الموقع' : 'Reach by location'}</h2><p>{language === 'ar' ? 'التغطية الجغرافية المسجلة' : 'Recorded geographic coverage'}</p></div><MapPin size={20}/></header><div className="location-list">{data.beneficiaries.map(item => { const total = item.men + item.women + item.boys + item.girls; return <div key={item.id}><span className="location-pin"><MapPin size={17}/></span><div><strong>{item.location}</strong><small>{data.projects.find(p => p.id === item.projectId)?.name}</small></div><span>{formatNumber(total, language)}</span></div>})}</div></article></section>
  </>
}
